pipeline {
  agent { label 'agent' }
  stages {
    stage('deploy voteapp') {
      steps {
        sh '''
        detc create \
        --plan https://raw.githubusercontent.com/lacework-dev/detc-resources/main/plans/voteapp/voteapp-eks.yml \
        --trace \
        --apply
       '''
      }
    }
  }
}

