credentials:
  system:
    domainCredentials:
      - credentials:
        - basicSSHUserPrivateKey:
            id: "jenkins-agents"
            scope: GLOBAL
            username: ${JENKINS_AGENT_USER}
            privateKeySource:
              directEntry:
                privateKey: |
                  ${JENKINS_AGENT_PRIV_KEY}
        - usernamePassword:
            id: "dockerhub-access-token"
            username: ${DOCKERHUB_ACCESS_USER}
            password: ${DOCKERHUB_ACCESS_TOKEN}
        - string:
            id: "lw-access-token"
            secret: ${LW_ACCESS_TOKEN}
            description: "lw access token"
        - string:
            id: "lw-account-name"
            secret: ${LW_ACCESS_ACCOUNT}
            description: "lw account name"
        - string:
            id: "k8s-cluster-name"
            secret: ${K8S_CLUSTER_NAME}
        - string:
            id: "k8s-context-name"
            secret: ${K8S_CONTEXT_NAME}
        - string:
            id: "k8s-server-url"
            secret: ${K8S_SERVER_URL}
        - string:
            id: "k8s-build-robot-token"
            secret: ${K8S_BUILD_ROBOT_TOKEN}

jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"

security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: "triggeringUsersAuthorizationStrategy"

unclassified:
  location:
    url: http://${SERVER}:8080/

jobs:
  - script: >
      job('Job_DSL_Seed') {
        scm {
          git {
            remote {
              url 'https://github.com/lacework-dev/detc-resources.git'
            }
          }
        }
        steps {
          jobDsl {
            targets 'apps/jenkins/job-seeds/**/*.groovy'
          }
        }
      }
