---
    post_tenant_setup:
      description: |
        This plan runs through a variety of setup tasks required to make the full DETC environment work properly.
      steps:
        - name: attach-admin-policy-eks-role
          extension: Ansible
          tags: lacwork
          source:
            location: "git+https://github.com/lacework-dev/detc-resources.git"
            subdir: "util/tenant_setup/ansible/"
          args:
            hosts: localhost
            connection: local
            inventory: localhost
            playbook:
              - attach-admin-policy-eks-role.yml
            extra_vars:
              aws_access_key: !secret aws.access_key
              aws_secret_key: !secret aws.secret_key
              aws_region: !secret aws.region
        - name: update-cspm-policies
          extension: Ansible
          tags: lacwork
          source:
            location: "git+https://github.com/lacework-dev/detc-resources.git"
            subdir: "util/tenant_setup/ansible/"
          args:
            hosts: localhost
            connection: local
            inventory: localhost
            playbook:
              - update-cspm-policies.yml
            extra_vars:
              lacework_account_name: !secret lacework.account_name
              lacework_subaccount_name: !secret lacework.subaccount_name
              lacework_api_key: !secret lacework.api_key
              lacework_api_secret: !secret lacework.api_secret
