---
    post_tenant_setup:
      description: |
        This plan runs through a variety of setup tasks required to make the full DETC environment work properly.
      steps:
        - name: gcp-prereqs
          extension: Terraform
          tags: gcp
          source:
            location: "git+https://github.com/lacework-dev/detc-resources.git"
            subdir: "util/tenant_setup/terraform/gcp"
          args:
            cloud: gcp
            outputs:
              - service_account
            tfvars:
              region: !secret gcp.region
              project: !secret gcp.project_id
        - name: attach-admin-policy-eks-role
          extension: Ansible
          tags: lacwork
          source:
            location: "git+https://github.com/lacework-dev/detc-resources.git"
            subdir: "util/tenant_setup/ansible/"
          args:
            hosts: localhost
            connection: local
            inventory: localhost
            playbook:
              - attach-admin-policy-eks-role.yml
            extra_vars:
              aws_access_key: !secret aws.access_key
              aws_secret_key: !secret aws.secret_key
              aws_region: !secret aws.region
