pipeline {
  agent { label 'agent' }
  stages {
    stage('teardown-all') {
      when {
        expression {
          input message: "Really, teardown all apps?"
          return true
        }
      }

      steps {
        sh '''
          detc destroy \
          --plan https://raw.githubusercontent.com/lacework-dev/detc-resources/main/plans/voteapp/voteapp-aks.yml \
          --plan https://raw.githubusercontent.com/lacework-demo/unhackable-ecommerce-app/main/deploy/ecommerce-eks.yaml \
          --plan https://raw.githubusercontent.com/lacework-demo/ticketing-app/main/deploy/ticketing-gcp.yaml \
          --plan https://raw.githubusercontent.com/lacework-dev/detc-resources/main/plans/k8s/aks.yaml \
          --plan https://raw.githubusercontent.com/lacework-dev/detc-resources/main/plans/k8s/eks.yaml \
          --plan https://raw.githubusercontent.com/lacework-dev/detc-resources/main/plans/k8s/gke.yaml \
          --trace \
          --apply
       '''
      }
    }
  }
}

