---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lacework-config
data:
  config.json: |
    {
      "autoupgrade": "disable",
      "tokens": {"AccessToken":"{{ index . "lw_access_token" }}"},
      "tags":{"Env":"k8s","KubernetesCluster":"{{.cluster_name}}"},
      "serverurl":{{if .fra}}"https://agent.euprodn.lacework.net"{{else}}"https://agent.lacework.net"{{end}}
    }
