- name: "Install jenkins-agent"
  hosts: all

  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

    - name: add gcloud repo
      shell: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" |  tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

    - name: add gcloud gpg
      shell: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg |  tee /usr/share/keyrings/cloud.google.gpg

    - name: Update repositories cache and install gcloud packages
      ansible.builtin.apt:
        pkg:
          - google-cloud-cli
          - google-cloud-sdk-gke-gcloud-auth-plugin
          - kubectl
        update_cache: yes

  vars:
    master_host: "{{ jenkins_server_url }}"
    master_user: "{{ jenkins_admin_id }}"
    master_password:  "{{ jenkins_admin_pass }}"
    slave_linux_jenkins_cred_id: "jenkins-agents"
    slave_linux_jenkins_username: "{{ slave_linux_jenkins_username }}"
    slave_linux_jenkins_group: "docker"
    slave_linux_jenkins_public_key: "{{ jenkins_agent_pub_key }}"
    slave_executors_num: 2
    nodejs_version: "16.x"

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-11-jdk
    - role: geerlingguy.nodejs
    - role: lean_delivery.jenkins_slave


- name: "Setup DETC Tool"
  hosts: all
  tasks:
    - name: create gcp auth file
      copy:
        dest: "/home/{{ slave_linux_jenkins_username }}/.gcp.json"
        content: "{{ gcp_service_account_file_content | from_json }}"
    
    - name: Create detc dirs
      ansible.builtin.file:
        path: "/home/{{ slave_linux_jenkins_username }}/.detc/config"
        state: directory
        mode: '0755'
        owner: "{{ slave_linux_jenkins_username }}"

    - name: create detc config
      template:
        src: templates/detc.toml.j2
        dest: "/home/{{ slave_linux_jenkins_username }}/.detc/config/default.toml"
        mode: 0755
        owner: "{{ slave_linux_jenkins_username }}"

    - name: install detc
      shell: 'curl https://detc-artifacts.s3.amazonaws.com/install.sh | bash'
