---
azure-k8s:
  steps:
    - name: k8s
      extension: AKS
      args:
        deployment_name: sharedaks
        azure_app_id: !secret azure.app_id
        azure_password: !secret azure.password
        azure_subscription_id: !secret azure.subscription_id
        azure_tenant_id: !secret azure.tenant_id
        azure_location: !secret azure.region
    - name: lacework
      extension: Kubectl
      description: This step deploys Lacework instrumentation to an existing K8s cluster
      tags: monitoring
      source:
        location: "git+https://github.com/lacework-dev/detc-resources.git"
        subdir: "apps/lacework"
        templates:
          - "config.yml"
      needs:
        - k8s
      helpers:
        - helper: WriteValue
          run_on_dryrun: true
          args:
            raw_value: !lookup /k8s/outputs/kubectl_config
            dstfile: kubectl
      args:
        lw_access_token: !secret lacework.access_token
        kubectl_config_file: kubectl
        kube_manifest_path: "."
        cluster_name: sharedaks
