---
kubernetes:
  steps:
    - name: k8s
      extension: AKS
      args:
        deployment_name: sharedaks
        azure_app_id: !secret azure.app_id
        azure_password: !secret azure.password
        azure_subscription_id: !secret azure.subscription_id
        azure_tenant_id: !secret azure.tenant_id
    - name: lacework
      extension: Kubectl
      description: This step deploys Lacework instrumentation to an existing K8s cluster
      tags: monitoring
      source:
        location: "https://raw.githubusercontent.com/lacework-dev/detc-resources/main/apps/lacework-all-k8s.yaml"
        templates:
          - "lacework-all-k8s.yaml"
      needs:
        - k8s
      helpers:
        - helper: WriteValue
          run_on_dryrun: true
          args:
            name: kubectl_config
            dstfile: kubectl
      lookup:
        control_plane_url: /k8s/outputs/cluster_endpoint
        kubectl_config: /k8s/outputs/kubectl_config
      args:
        lw_access_token: !secret lacework.access_token
        kubectl_config_file: kubectl
        kube_manifest_path: "lacework-all-k8s.yaml"

