---
kubernetes:
  steps:
    - name: k8s
      extension: EKS
      description: This step uses the EKS extension (Terraform under the hood) to deploy the actual cluster. Expect runtimes in excess of 10 minutes
      args:
        region: us-east-2
        deployment_name: sharedeks
    - name: lacework
      extension: Kubectl
      description: This step deploys Lacework instrumentation to an existing K8s cluster
      tags: monitoring
      source:
        location: "git+https://github.com/lacework-dev/detc-resources.git"
        subdir: "apps/lacework"
        templates:
          - "config.yml"
      needs:
        - k8s
      helpers:
        - helper: WriteValue
          run_on_dryrun: true
          args:
            raw_value: !lookup /k8s/outputs/kubectl_config
            dstfile: kubectl
      args:
        lw_access_token: !secret lacework.access_token
        kubectl_config_file: kubectl
        kube_manifest_path: "."
        cluster_name: "shared-eks"
