---
aws-k8s:
  description: Deploy EKS with CIS Compliance Scanning enabled
  required_secrets:
    - path: lacework.account_name
    - path: lacework.access_token
  steps:
    - name: k8s
      extension: EKS
      description: This step uses the EKS extension (Terraform under the hood) to deploy the actual cluster. Expect runtimes in excess of 10 minutes
      args:
        region: !secret aws.region
        cluster_name: sharedeks
      helpers:
        - helper: EKSKubectl
          lifecycle: [ afterCreate ]
    - name: deploy-agent
      extension: Helm
      source:
        location: https://raw.githubusercontent.com/lacework-dev/detc-resources/main/apps/lacework-agent-helm/values.yaml
        templates:
          - values.yaml
      needs:
        - k8s
      helpers:
        - helper: WriteValue
          run_on_dryrun: true
          args:
            raw_value: !lookup /aws-k8s/k8s/outputs/kubectl_config
            dstfile: kube.conf
      args:
        kubectl_config_file: kube.conf
        repos:
          - name: lacework
            url: https://lacework.github.io/helm-charts
        name: lacework-agent
        namespace: lacework
        chart: lacework/lacework-agent
        account_name: !secret lacework.account_name
        access_token: !secret lacework.access_token
        cluster_name: !lookup /aws-k8s/k8s/outputs/cluster_name
        region: !secret aws.region
        value_files:
          - values.yaml

