
- https://raw.githubusercontent.com/lacework-dev/detc-resources/main/apps/lacework-accounts/integrate_accounts.yml
- https://raw.githubusercontent.com/lacework-dev/detc-resources/main/plans/util/post_deployment_setup.yaml
