laceworkConfig:
  serverUrl: {{ or .api_url "https://agent.lacework.net" }}
  accessToken: {{ .access_token }}
  kubernetesCluster: {{ .cluster_name }}
  codeaware:
    enable: experimental
{{ if eq .enable_cluster_agent "true" }}
clusterAgent:
  enable: True
  image:
    tag: {{ or .cluster_agent_tag "latest" }}
    repository: "lacework/k8scollector"
  clusterType: {{ .cluster_type }}
  clusterRegion: {{ .region }}
{{ end }}
{{ if ne .enable_cluster_agent "true" }}
clusterAgent:
  enable: False
{{ end }}
image:
  repository: "lacework/datacollector"
  tag: {{ or .agent_tag "latest" }}

