proxy-scanner:
  config:
    scan_public_registries: true
    default_registry: index.docker.io
    static_cache_location: /opt/lacework
    lacework:
      account_name: {{ .account_name }}
      integration_access_token: {{ .admission_controller_token }}
    registries:
      - domain: index.docker.io
        name: dockerhub
        ssl: true
        auto_poll: false
        is_public: true
        poll_frequency_minutes: 20
        disable_non_os_package_scanning: false
        go_binary_scanning:
          enable: true
    admission:
      excluded_resources:
        - DaemonSet
        - Job
        - CronJob
        - StatefulSet
